title: No Crows Permitted
description: A website emphasizing the importance of NO CROWS!!!!
baseurl: ""
url: ""
theme: minima

plugins:
  - jekyll-feed

header_pages:  
  - projects.md
  - contact.md
  - about.md
